version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
      - phpmyadmin
    networks:
      - alef

  db:
    image: mysql
    container_name: alef_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - alef

  # Application Service
  php-fpm:
    container_name: alef_php
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www
      - ./php/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9001:9000"
    working_dir: /var/www
    networks:
      - alef
    environment:
      PHP_IDE_CONFIG: serverName=Docker

  phpmyadmin:
    container_name: alef_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - alef

networks:
  alef:
    driver: bridge
